### ISSUE TITLE
Метод с элипсами

### ISSUE THREAD

**Issue by dj-kostya** [dj-kostya/farich-detector#1]
# Метод фитинга элипсов

## Принцип работы

1. Выбрать 6 точек
2. Попробовать построить плоскость по 6 точкам
3. Спроецировать все точки на плоскость, которые находятся на ней на расстоянии не более чем $\varepsilon$
4. Построить элипс по 6 точкам
5. Вернуть центр и точки, которые попали на элипс
6. Повторить 1 пока не переберем все точки
7. Выбрать центр и соответсвующие точки

## TODO

- [ ] Посчитать метрики с шумом
- [x] Возврат точек из метода фит элипс
- [x] Выбор центра
- [ ] Подбор параметров алгоритма

**Comment by dj-kostya** [comment]
Принято решение приостановить работу по данному направлению
